/* Реальные названия авто в автосалонах */
export default {
/* Добавляете сюда свои авто, по примеру: */
/* "название_veh": "Реальное название которое будет показано" */

"e55":"Mercedes E55",
"c63w204":"Mercedes C63 W204",
"cls63s":"Mercedes CLS 63S",
"c63coupe":"Mercedes C63 COUPE",
"g500":"Mercedes G500",
"gls63":"Mercedes GLS 63",
"g65":"Mercedes G65",
"amggt":"Mercedes AMG GT",
"s63":"Mercedes S63",
"g65amg":"Mercedes G65 AMG",
"brabusgt":"Mercedes Brabus GT",
"maybach":"Mercedes Maybach",
"s63w222":"Mercedes S63 W222",
"gle53":"Mercedes GLE 53",
"vclass":"Mercedes V-CLASS",
"6x6":"Mercedes 6X6",
"pullman":"Mercedes Pullman",
"bmwe34":"BMW E34",
"bmwe38":"BMW E38",
"x5e53":"BMW X5 E53",
"m5e60":"BMW M5E60",
"x5m":"BMW X5M",
"m2":"BMW M2",
"i8":"BMW I8",
"7bmw":"BMW 7 SERIES",
"m4comp":"BMW M4 COMPETITION",
"m5f90":"BMW M5 F90",
"bmwx7":"BMW X7",
"m8":"BMW M8",
"2101":"Lada 2101",
"2103":"Lada 2103",
"2105":"Lada 2105",
"2109samara":"Lada 2109 Samara",
"oka":"Lada Oka",
"volga":"Lada Volga",
"priora":"Lada Priora",
"vesta":"Lada Vesta",
"RRSVR":"Ravara",

// moto
"cbr1000rrr": "Honda CBR 1000 RR",
"cbr650r": "Honda СBR650R",
"bmw1000": "BMW S1000 RR",
"ducatileggera": "Ducati Leggera v4",
"Iron883": "Harley-Davidson Sportster 883",
"kawasakiz1000": "Kawasaki Z 1000",
"ktmduke": "KTM 390 Duke",
"r1": "Yamaha YZF-R1",
"z800": "Kawasaki Z800",

// aero room
"Buzzard2": "Buzzard2",
"Mammatus": "Mammatus",
"Luxor2": "Luxor2",

// авто-донат
"ae86": "Toyota AE86",
"rs6c5": "Audi RS6 C5",
"civic6": "Honda Civiv",
"camryv40": "Toyota Camry V40",
"z350": "Nissan 350Z",
"impala": "Chevrolet Impala",
"octavia": "Skoda Octavia",
"subisti08": "Subaru WRX STi",
"evo9": "Mitsubishi Lancer Evolution IX",
"rx7": "Mazda RX7",
"skyline": "Nissan Skyline",
"xfr": "Jaguar XFR",
"camryv55": "Toyota Camry V55",
"subaru": "Buzzard2",
"mini2020": "MINI Cooper 2020",
"srt8": "Jeep Grand Cherokee SRT8",
"evo10": "Mitsubishi Lancer Evolution X",
"svr": "Range Rover Sport SVR",
"supra": "Toyota Supra",
"rcf": "Lexus RC F",
"a6": "Audi A6",
"giulia": "Alfa Romeo Giulia",
"mustang65": "1965 Ford Mustang",
"camryv70": "Toyota Camry V70",
"camaro2012": "Chevrolet Camaro 2012",
"xc90": "Volvo XC90",
"jeep4x4": "Jeep 4x4",
"land200": "Toyota Land 200",
"veilside": "Veilside",
"chevelless": "Chevrolet Chevelle",
"69charger": "Dodge Charger 69",
"ttrs": "Audi TT RS",
"panamera": "Porsche Panamera",
"rs6": "Audi RS6",
"gtr": "Nissian GTR",
"gtrr50": "Nissan GTR R50",
"16charger": "Dodge Charger 2016",
"ftype": "Jaguar F-Type",
"rs7": "Audi RS7",
"nissantitan17": "Nissan Titan 2017",
"mustangr": "Ford Mustang",
"supra2020": "Toyota Supra 2020",
"maserati": "Maserati",
"escalade": "Cadillac Escalade",
"camaro": "Chevrolet Camaro",
"caynne18": "Porsche Cayenne",
"ctsv16": "Cadillac CTS-V 2016",
"continental": "Bentley Continental",
"portofino": "Ferrari Portofino",
"r820": "Audi R8 2020",
"911": "Porsche 911",
"corvettec8": "Chevrolet Corvette (C8)",
"ff": "Ferrari FF",
"bentyaga18": "Bentley Bentayga",
"rculi": "Rolls Royce Cullinan",
"wraith": "Rolls-Royce Wraith",
"huracan": "Lamborghini Huracán",
"svj": "Lamborghini Aventador SVJ",
"sian": "Lamborghini Sian",
"agerars": "Koenigsegg Agera R",
"urus": "Lamborghini Urus",
"chiron": "Bugatti Chiron",
"divo": "Bugatti DIVO",
"tesroad20": "Tesla Roadster",

"mb300sl": "Mercedes-Benz 300 SL",
"maybachpolice": "Mercedes Maybach Police",
"vision6": "Mercedes Vision",
"eqg": "Mercedes EQG 2022",

}